// this file maps FFL enums to strings for displaying errors, etc.

#include <nn/ffl.h>

// TODO: CAN YOU REDUCE THIS???
const char* FFLiVerifyCharInfoReasonStrings[] = {
    "FFLI_VERIFY_CHAR_INFO_REASON_OK",
    // NOTE: AFLiVerifyCharInfoWithReason has the names of
    // the CharInfo parts in its logging
    "FFLI_VERIFY_CHAR_INFO_REASON_FACE_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_FACELINE_COLOR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_FACE_LINE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_FACE_MAKE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_HAIR_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_HAIR_COLOR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_HAIR_DIR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYE_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYE_COLOR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYE_SCALE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYE_SCALE_Y_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYE_ROTATE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYE_SPACING_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYE_POS_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYEBROW_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYEBROW_COLOR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYEBROW_SCALE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYEBROW_SCALE_Y_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYEBROW_ROTATE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYEBROW_SPACING_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_EYEBROW_POS_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_NOSE_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_NOSE_SCALE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_NOSE_POS_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOUTH_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOUTH_COLOR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOUTH_SCALE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOUTH_SCALE_Y_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOUTH_POS_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_BEARD_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_BEARD_COLOR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MUSTACHE_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MUSTACHE_SCALE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MUSTACHE_POS_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_GLASS_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_GLASS_COLOR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_GLASS_SCALE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_GLASS_POS_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOLE_TYPE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOLE_SCALE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOLE_POS_X_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_MOLE_POS_Y_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_HEIGHT_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_BUILD_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_NAME_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_CREATOR_NAME_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_GENDER_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_BIRTHDAY_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_FAVORITE_COLOR_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_REGION_MOVE_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_FONT_REGION_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_PAGE_INDEX_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_SLOT_INDEX_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_BIRTH_PLATFORM_INVALID",
    "FFLI_VERIFY_CHAR_INFO_REASON_CREATOR_ID_INVALID"
};

/* NOTE: the following is the real enum:
typedef enum FFLResult
{
    FFL_RESULT_SUCCESS                   =  0,
    FFL_RESULT_WRONG_PARAM               =  1,
    FFL_RESULT_DB_NO_DATA                =  2,
    FFL_RESULT_BROKEN                    =  3,
    FFL_RESULT_NOT_AVAILABLE             =  4,
    FFL_RESULT_FATAL                     =  5,
    FFL_RESULT_LOAD_FAIL                 =  6,
    FFL_RESULT_SAVE_FAIL                 =  7,
    FFL_RESULT_BUSY                      =  8,
    FFL_RESULT_NAND_COMMAND_FAIL         =  9,
    FFL_RESULT_FORMATTED                 = 10,
    FFL_RESULT_DB_FULL                   = 11,
    FFL_RESULT_TEMP_MEMORY_SHORT         = 12,
    FFL_RESULT_INTERNAL0                 = 13,
    FFL_RESULT_INTERNAL1                 = 14,
    FFL_RESULT_INTERNAL2                 = 15,
    FFL_RESULT_FAILED_SYSTEM0            = 16,
    FFL_RESULT_FAILED_ACT                = 17,
    FFL_RESULT_FAILED_FS                 = 18,
    FFL_RESULT_RUN_MII_STUDIO            = 19
}
FFLResult;
*/
const char* FFLResultStrings[] = {
    "FFL_RESULT_OK",
    "FFL_RESULT_ERROR",
    "FFL_RESULT_HDB_EMPTY",
    "FFL_RESULT_FILE_INVALID",
    "FFL_RESULT_MANAGER_NOT_CONSTRUCT",
    "FFL_RESULT_FILE_LOAD_ERROR",
    "FFL_RESULT_UNKNOWN_6",
    "FFL_RESULT_FILE_SAVE_ERROR",
    "FFL_RESULT_UNKNOWN_8",
    "FFL_RESULT_RES_FS_ERROR",
    "FFL_RESULT_ODB_EMPTY",
    "FFL_RESULT_UNKNOWN_11",
    "FFL_RESULT_OUT_OF_MEMORY",
    "FFL_RESULT_UNKNOWN_13",
    "FFL_RESULT_UNKNOWN_14",
    "FFL_RESULT_UNKNOWN_15",
    "FFL_RESULT_UNKNOWN_16",
    "FFL_RESULT_UNKNOWN_17",
    "FFL_RESULT_FS_ERROR",
    "FFL_RESULT_FS_NOT_FOUND"
};



#include <stdio.h>

#define UNKNOWN "(unknown)"

const char* FFLiVerifyCharInfoReasonToString(FFLiVerifyCharInfoReason reason)
{
    // make sure it is in range
    if (reason < 0 || reason > FFLI_VERIFY_CHAR_INFO_REASON_CREATOR_ID_INVALID)
        return UNKNOWN;

    return FFLiVerifyCharInfoReasonStrings[reason];
}

const char* FFLResultToString(FFLResult result)
{
    // make sure it is in range
    if (result < 0 || result > FFL_RESULT_FS_NOT_FOUND)
        return UNKNOWN;

    return FFLResultStrings[result];
}
